
```{r message=FALSE, warning=FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(readxl)
library(reshape)
library(tidyr)

data_all <- read_xlsx("../data/DatenbefragungAll_xlsx.xlsx")
```

```{r message=FALSE, warning=FALSE}
data_ein <- data_all %>% select(c("te_einwohner", "te_einwohner_2","sdf_wohnort")) %>% na.omit()

# transforming the answers
data_ein$te_einwohner[data_ein$te_einwohner == "te_einwohner_wohnort"] <- "Als Einwohner/in Ihres Wohnortes"
data_ein$te_einwohner[data_ein$te_einwohner == "te_einwohner_bodenseeregion"] <- "Als Einwohner/in der Bodenseeregion"

data_ein$te_einwohner_2[data_ein$te_einwohner_2 == "te_einwohner_de"] <- "Als Deutsche/r"
data_ein$te_einwohner_2[data_ein$te_einwohner_2 == "te_einwohner_au"] <- "Als Österreicher/in"
data_ein$te_einwohner_2[data_ein$te_einwohner_2 == "te_einwohner_ch"] <- "Als Schweizer/in"
data_ein$te_einwohner_2[data_ein$te_einwohner_2 == "te_einwohner_li"] <- "Als Liechtensteiner/in"
data_ein$te_einwohner_2[data_ein$te_einwohner_2 == "te_einwohner_europa"] <- "Als Europäer/in"

data_ein$sdf_wohnort[data_ein$sdf_wohnort == "de"] <- "Deutschland"
data_ein$sdf_wohnort[data_ein$sdf_wohnort == "au"] <- "Österreich"
data_ein$sdf_wohnort[data_ein$sdf_wohnort == "ch"] <- "Schweiz"
```


## Einwohner Wohnort vs Bodenseeregion
```{r message=FALSE, warning=FALSE}
wohn_boden <- data_ein %>% select(-c(te_einwohner_2)) %>% group_by(te_einwohner, sdf_wohnort) %>%
  summarise(occurences = n())

# Schweiz
wohn_boden_ch <- wohn_boden %>% filter(sdf_wohnort == "Schweiz")
wohn_boden_ch <- wohn_boden_ch %>% mutate(
  Prozent = round((occurences/sum(wohn_boden_ch$occurences)*100),2)
                                          )
# Deutschland
wohn_boden_de <- wohn_boden %>% filter(sdf_wohnort == "Deutschland")
wohn_boden_de <- wohn_boden_de %>% mutate(
  Prozent = round((occurences/sum(wohn_boden_de$occurences)*100),2)
                                          )
# Österreich
wohn_boden_au <- wohn_boden %>% filter(sdf_wohnort == "Österreich")
wohn_boden_au <- wohn_boden_au %>% mutate(
  Prozent = round((occurences/sum(wohn_boden_au$occurences)*100),2)
                                          )

# Bringing all together
wohn_boden <- rbind(wohn_boden_de, wohn_boden_au, wohn_boden_ch)

# N = 264
```

## Plot Selbstverständnis Einwohner Wohnort vs. Bodenseeregion
```{r message=FALSE, warning=FALSE}

ggplot(data = wohn_boden, aes(te_einwohner,Prozent, fill = sdf_wohnort)) +
  geom_col(position = "dodge", alpha = 0.8) + xlab(" ") + ylab("Prozent %") +
  geom_text(aes(label = Prozent),
            position=position_dodge(width=0.9), size = 3,vjust=-0.5) +
  ggtitle("Wie würden Sie sich selbst am ehesten bezeichnen? (Wohnort vs. Bodenseeregion)") + ylim(0,100) + 
  theme(plot.title = element_text(size = 11, face = "bold"),legend.title = element_blank(), legend.position="bottom",
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10,face = "bold"),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10,face = "bold")) + 
   scale_fill_manual(values = c("#252525", "#bdbdbd", "#de2d26"))

ggsave("to_deliver/Wohnort_vs_Bodensee.pdf")
```


## Einwohner Nationalstaat vs. Europa

```{r message=FALSE, warning=FALSE}
nat_eur <- data_ein %>% select(-c(te_einwohner)) %>% group_by(te_einwohner_2, sdf_wohnort) %>%
  summarise(occurences = n())

# Deutschland
nat_eur_de <- nat_eur %>% filter(sdf_wohnort == "Deutschland")
nat_eur_de <- nat_eur_de %>% mutate(Prozent = round((occurences/sum(nat_eur_de$occurences))*100,2))

# Österreich
nat_eur_au <- nat_eur %>% filter(sdf_wohnort == "Österreich")
nat_eur_au <- nat_eur_au %>% mutate(Prozent = round((occurences/sum(nat_eur_au$occurences))*100,2))

# Schweiz
nat_eur_ch <- nat_eur %>% filter(sdf_wohnort == "Schweiz")
nat_eur_ch <- nat_eur_ch %>% mutate(Prozent = round((occurences/sum(nat_eur_ch$occurences))*100,2))

# bringing back alltogether
nat_eur <- rbind(nat_eur_de, nat_eur_au, nat_eur_ch)
```

## Plot Einwohner Nationalstaat vs. Europa
```{r message=FALSE, warning=FALSE}

ggplot(data = nat_eur, aes(te_einwohner_2, Prozent, fill = sdf_wohnort)) +
  geom_col(position = "dodge", alpha = 0.8) + xlab(" ") + ylab("Prozent %") +
  geom_text(aes(label = Prozent),
            position=position_dodge(width=0.9), size = 3,vjust=-0.5) +
  ggtitle("Wie würden Sie sich selbst am ehesten bezeichnen? (Nationalstaat vs. Europa)") + ylim(0,100) + 
  theme(plot.title = element_text(size = 11, face = "bold"),legend.title = element_blank(), legend.position="bottom",
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10,face = "bold"),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10,face = "bold")) + 
   scale_fill_manual(values = c("#252525", "#bdbdbd", "#de2d26"))

ggsave("to_deliver/national_vs_europa.pdf")
```


