---
title: ''
author: "Nikos Bakogiannis"
date: "19 11 2021"
output: html_document
---

```{r import data, message=FALSE, warning=FALSE, include=FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(readxl)
library(reshape)
library(tidyr)


data_all <- read_xlsx("../data/DatenbefragungAll_xlsx.xlsx")

df_f1 <- data_all %>% select(., c("te_tourist_einheimisch","sdf_geschlecht",
                               "sdf_jahrgang", "te_gruende_tourist")) %>%
  filter(., te_tourist_einheimisch == "tourist") %>% group_by(
    
 sdf_jahrgang, te_gruende_tourist)

# Aus welchen Gründen haben Sie sich für einen Ausflug in die Bodenseeregion entschieden?

gruende <- unlist(strsplit(df_f1$te_gruende_tourist, ",")) %>% as.data.frame()
names(gruende) <- "Ausflug_Gruende"

gruende <- table(gruende) %>% as.data.frame()
#gruende$Ausflug_Gruende <- as.character(gruende$Ausflug_Gruende)

gruende <- gruende %>% mutate(
  percent = round((Freq/sum(Freq)*100),2)
)

levels(gruende$gruende)[1:14] <- c("Erholung","Freunde","Gastronomie","Gesundheit","Gewohnheit",
                                   "Inspiration","Internationalität","Kultur","Nähe","Natur",
                                   "Shopping","Sonstiges","Sport","Ich weiss nicht") 

p_gruende <- ggplot(gruende, aes(percent, gruende, fill=gruende,alpha = 0.85)) + geom_col()  + 
  xlab("Prozent %") + ylab(" ") +
  geom_text(aes(label = percent), size = 3,hjust=-0.5) +  
  ggtitle("Aus welchen Gründen haben Sie sich für einen Ausflug in die\nBodenseeregion entschieden?") + xlim(0,30) + 
  theme(plot.title = element_text(size = 11, face = "bold"),legend.position="none",
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10,face = "bold"),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10,face = "bold")) 


#ggsave("to_deliver/grund_ausflug.pdf")

# df_gruende <- gruende %>% as.data.frame()
#write.csv(df_gruende,"to_deliver/tables/gruende_ausflug.csv", row.names = F)
```

## te_erlebnisse
```{r  message=FALSE, warning=FALSE, include=FALSE}
df_f2 <- data_all %>% select(., c("te_tourist_einheimisch","sdf_geschlecht",
                               "sdf_jahrgang", "te_erlebnisse")) %>%
  filter(.,te_tourist_einheimisch == "tourist") %>% 
  group_by(te_erlebnisse,sdf_jahrgang)


erlebnisse <- unlist(strsplit(df_f2$te_erlebnisse, ",")) %>% as.data.frame()

erlebnisse <- table(erlebnisse) %>% as.data.frame() # getting the frequencies


erlebnisse <- erlebnisse %>% mutate(
  percent = round((Freq/sum(Freq)*100),2)
)

levels(erlebnisse$erlebnisse)[1:9] <- c("Abenteuer","Erholung","Gesundheit","Kultur",
                                        "Natur","Party","Shopping","Sonstiges","Sport")


p_erlebnisse <- ggplot(erlebnisse, aes(percent, erlebnisse, fill=erlebnisse,alpha = 0.85)) + geom_col()  + 
  xlab("Prozent %") + ylab(" ") +
  geom_text(aes(label = percent), size = 3,hjust=-0.5) +  
  ggtitle("Für welche Erlebnisse sehen Sie die\nBodenseeregion als besonders geeignet an?") + xlim(0,30) + 
  theme(plot.title = element_text(size = 11, face = "bold"),legend.position="none",
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10,face = "bold"),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10,face = "bold")) 

ggsave("to_deliver/erlebnisse_bodensee.pdf")
# 
# df_erlebnisse <- erlebnisse %>% as.data.frame()
# write.csv(df_erlebnisse,"to_deliver/tables/erlebnisse_bodensee.csv", row.names = F)
```

```{r}
df_f3 <- data_all %>% select(., c("te_tourist_einheimisch","te_anrainerstaat",
                               "te_anrainer_orte")) %>% filter(.,te_tourist_einheimisch=="tourist")

df_f3_1 <- df_f3 %>% select(.,"te_anrainerstaat") %>% na.omit() %>%
  table() %>% as.data.frame()
names(df_f3_1) <- c("Besuch","Freq")

df_f3_1 <- df_f3_1 %>% mutate(
  percent = round((Freq/sum(Freq)*100),2)
)


p_besuch <- ggplot(df_f3_1, aes(x = "", y = percent, fill = Besuch)) +
  geom_col() + xlab(" ") + ylab("% Prozent") +
  geom_text(aes(label = percent),
            position = position_stack(vjust = 0.5), size = 3) + ggtitle("Planen Sie während Ihres aktuellen Aufenthalts einen Besuch\nin einem anderen Anrainerstaat des Bodensees?") + 
  coord_polar(theta = "y") + scale_fill_manual(values = c("lightsteelblue2", "lightpink2")) + 
  theme(plot.title = element_text(size = 11, face = "bold"),
        legend.title = element_blank(), legend.position = "bottom",
        axis.title.x = element_text(size = 10,face = "bold"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid  = element_blank())

#ggsave("to_deliver/besuch_bodensee.pdf")


##### Wenn JA
df_f3_2 <- df_f3 %>% select(.,"te_anrainerstaat","te_anrainer_orte") %>% na.omit()


orte <- unlist(strsplit(df_f3_2$te_anrainer_orte, ",")) %>% as.data.frame()

orte <- table(orte) %>% as.data.frame()

orte <- orte %>% mutate(
  percent = round((Freq/sum(Freq)*100),2)
)

levels(orte$orte) <- c("Allensbach","Bregenz","Dornbirn","Feldkirch","Friedrichshafen","Konstanz",
                       "Kreuzlingen","Lindau","Meersburg","Radolfzell","Ravensburg","Romanshorn",
                       "Singen","Sonstiges","St_gallen","Stein_am_rhein","Überlingen","Winterthur")

p_orte <- ggplot(orte, aes(percent, orte, fill=orte, alpha = 0.85)) + geom_col()  + 
  xlab("Prozent %") + ylab(" ") +
  geom_text(aes(label = percent), size = 3,hjust=-0.5) +  
  ggtitle("An welchen Orten planen Sie während Ihres aktuellen Aufenthalts\neinen Besuch in einem anderen Anrainerstaat des Bodensees?") + xlim(0,30) + 
  theme(plot.title = element_text(size = 11, face = "bold"),legend.position="none",
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10,face = "bold"),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10,face = "bold"))

ggsave("to_deliver/besuch_bodensee_JA.pdf")
```

```{r}
df_f4 <- data_all %>% select(., c("te_tourist_einheimisch","te_jahreszeit_fruehling",
                                  "te_jahreszeit_sommer","te_jahreszeit_herbst","te_jahreszeit_winter")) %>% filter(.,te_tourist_einheimisch == "tourist")


df_f5 <- data_all %>% select(., c("te_tourist_einheimisch","te_jahreszeit_natur",
                                  "te_jahreszeit_kultur")) %>% filter(.,te_tourist_einheimisch == "tourist")

df_f5_natur <- df_f5 %>% select(.,c("te_jahreszeit_natur")) %>% na.omit()
df_f5_kultur <- df_f5 %>% select(.,c("te_jahreszeit_kultur")) %>% na.omit()

# Natur
df_f5_natur <- unlist(strsplit(df_f5_natur$te_jahreszeit_natur, ",")) %>% as.data.frame()
df_f5_natur <- table(df_f5_natur) %>% as.data.frame()
df_f5_natur <- df_f5_natur %>% mutate(
  percent = round((Freq/sum(Freq))*100,2),
  type = "Natur"
)


# Kultur
df_f5_kultur <- unlist(strsplit(df_f5_kultur$te_jahreszeit_kultur, ",")) %>% as.data.frame()
df_f5_kultur <- table(df_f5_kultur) %>% as.data.frame()
df_f5_kultur <- df_f5_kultur %>% mutate(
  percent = round((Freq/sum(Freq))*100,2),
  type = "Kultur"
)

names(df_f5_natur)[1] <- c("Jahreszeit")
names(df_f5_kultur)[1] <- c("Jahreszeit")
df_kultur_natur <- rbind(df_f5_natur,df_f5_kultur)


## Plot
p6 <- ggplot(data = df_kultur_natur, aes(x = Jahreszeit, y = percent, fill = type)) +
  geom_col(position = "dodge", alpha = 0.8) + xlab(" ") + ylab("Prozent %") +
  geom_text(aes(label = percent),
            position=position_dodge(width=0.9), size = 3,vjust=-0.5) +
  ggtitle("") + ylim(0,100) +
  scale_fill_manual(values = c("plum2", "lightgreen")) + 
  theme(plot.title = element_text(size = 11, face = "bold"),legend.title = element_blank(), legend.position="bottom",
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10,face = "bold"),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10,face = "bold"))


## or 
p_natur <- ggplot(df_f5_natur, aes(x = "", y = percent, fill = Jahreszeit)) +
  geom_col() + xlab(" ") + ylab("% Prozent") +
  geom_text(aes(label = percent),
            position = position_stack(vjust = 0.5), size = 3) + ggtitle("Wann ist die Natur für den Aufenthalt in\nder Bodenseeregion besonders wichtig?") + 
  coord_polar(theta = "y") + scale_fill_manual(values = c("pink", "tan", "khaki","gray93","lightcoral","gray70")) + 
  theme(plot.title = element_text(size = 11, face = "bold"),
        legend.title = element_blank(), legend.position = "bottom",
        axis.title.x = element_text(size = 10,face = "bold"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid  = element_blank())

p_kultur <- ggplot(df_f5_kultur, aes(x = "", y = percent, fill = Jahreszeit)) +
  geom_col() + xlab(" ") + ylab("% Prozent") +
  geom_text(aes(label = percent),
            position = position_stack(vjust = 0.5), size = 3) + ggtitle("Wann ist die Kultur für den Aufenthalt in\nder Bodenseeregion besonders wichtig?") + 
  coord_polar(theta = "y") + scale_fill_manual(values = c("pink", "tan", "khaki","gray93","lightcoral","gray70")) + 
  theme(plot.title = element_text(size = 11, face = "bold"),
        legend.title = element_blank(), legend.position = "bottom",
        axis.title.x = element_text(size = 10,face = "bold"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid  = element_blank())


## OR combined in Pie charts
p_kultur_natur <- ggplot(data = df_kultur_natur, aes(x = "", y = percent, fill = Jahreszeit )) + 
    geom_bar(stat = "identity", position = position_fill()) +
    geom_text(aes(label = percent), position = position_fill(vjust = 0.5), size = 3) +
    coord_polar(theta = "y") + ggtitle("Wann ist die Kultur/Natur für den Aufenthalt in der Bodenseeregion\nbesonders wichtig?") +  ylab("% Prozent") + 
    facet_wrap(~ type) + scale_fill_manual(values = c("pink", "tan", "khaki","gray93","lightcoral","gray70")) +
  theme(plot.title = element_text(size = 11, face = "bold"),
          axis.title.x = element_text(size = 10,face = "bold"),
          axis.title.y = element_blank(),
          legend.title = element_blank(), legend.position='bottom',
          axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid  = element_blank()) 

ggsave("to_deliver/kultur_natur.pdf")
    
```


## Würden Sie noch einmal zu einer anderen Jahreszeit in der Bodenseeregion Ferien machen?
```{r}
dp9 <- data_all %>% select(c("te_jahreszeit_ja_nein","te_tourist_einheimisch")) %>%
  filter(., te_tourist_einheimisch == "tourist") %>% na.omit()

dp9 <- dp9 %>% group_by(te_jahreszeit_ja_nein,te_tourist_einheimisch) %>%
  summarise(occurences = n()) %>% mutate(
    percent = round((occurences/170)*100,2)
  )


p9_ferien <- ggplot(data = dp9, aes(x = "", y = percent, fill = te_jahreszeit_ja_nein )) + 
    geom_bar(stat = "identity", position = position_fill()) +
    geom_text(aes(label = percent), position = position_fill(vjust = 0.5), size = 3) +
    coord_polar(theta = "y") + ggtitle("Würden Sie noch einmal zu einer anderen Jahreszeit in der\nBodenseeregion Ferien machen?") +  ylab("% Prozent") + scale_fill_manual(values = c("palegreen1", "pink1", "gray80")) +
  theme(plot.title = element_text(size = 11, face = "bold"),
          axis.title.x = element_text(size = 10,face = "bold"),
          axis.title.y = element_blank(),
          legend.title = element_blank(), legend.position='bottom',
          axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid  = element_blank())

ggsave("to_deliver/ferien_ja_nein.pdf")
```

### Wie attraktiv finden Sie die Jahreszeiten für einen Urlaub in der Bodenseeregion?
```{r}
dp10 <- data_all %>% select(c("te_jahreszeit_attraktiv","te_jahreszeit_fruehling","te_jahreszeit_sommer",
                              "te_jahreszeit_herbst","te_jahreszeit_winter"))
```

```{r message=FALSE, warning=FALSE}
library(circlize)
dp11 <- data_all %>% select(c("te_anrainer", "te_tourist_einheimisch","befragungsort_list")) %>%
  filter(.,te_tourist_einheimisch == "tourist" & !is.na(te_anrainer) & !is.na(befragungsort_list))

dp11_filter <- dp11 %>% select(!te_tourist_einheimisch) %>% group_by(te_anrainer,befragungsort_list)


antworten <- unlist(strsplit(dp11_filter$te_anrainer, ",")) %>% as.data.frame()

# Bregenz
dp11_breg <- dp11 %>% filter(., befragungsort_list == "Bregenz")
antworten_breg <- unlist(strsplit(dp11_breg$te_anrainer, ",")) %>% as.data.frame() %>%
  mutate(Ort = "Bregenz")
names(antworten_breg)[1] <- "Antwort"
antworten_breg <- antworten_breg %>% group_by(Antwort,Ort) %>% summarise(occurences = n())

# Dornbin
dp11_dorn <- dp11 %>% filter(., befragungsort_list == "Dornbirn")
antworten_dorn <- unlist(strsplit(dp11_dorn$te_anrainer, ",")) %>% as.data.frame() %>%
  mutate(Ort = "Dornbin")
names(antworten_dorn)[1] <- "Antwort"
antworten_dorn <- antworten_dorn %>% group_by(Antwort,Ort) %>% summarise(occurences = n())

# Konstanz
dp11_kons <- dp11 %>% filter(., befragungsort_list == "Konstanz")
antworten_kons <- unlist(strsplit(dp11_kons$te_anrainer, ",")) %>% as.data.frame() %>%
  mutate(Ort = "Konstanz")
names(antworten_kons)[1] <- "Antwort"
antworten_kons <- antworten_kons %>% group_by(Antwort,Ort) %>% summarise(occurences = n())

# Meersburg
dp11_meer <- dp11 %>% filter(., befragungsort_list == "Meersburg")
antworten_meer <- unlist(strsplit(dp11_meer$te_anrainer, ",")) %>% as.data.frame() %>%
  mutate(Ort = "Meersburg")
names(antworten_meer)[1] <- "Antwort"
antworten_meer <- antworten_meer %>% group_by(Antwort,Ort) %>% summarise(occurences = n())

# Romanshorn
dp11_roman <- dp11 %>% filter(., befragungsort_list == "Romanshorn")
antworten_roman <- unlist(strsplit(dp11_roman$te_anrainer, ",")) %>% as.data.frame() %>%
  mutate(Ort = "Romanshorn")
names(antworten_roman)[1] <- "Antwort"
antworten_roman <- antworten_roman %>% group_by(Antwort,Ort) %>% summarise(occurences = n())

# St. Gallen
dp11_stga <- dp11 %>% filter(., befragungsort_list == "St. Gallen")
antworten_stgal <- unlist(strsplit(dp11_stga$te_anrainer, ",")) %>% as.data.frame() %>%
  mutate(Ort = "St. Gallen")
names(antworten_stgal)[1] <- "Antwort"
antworten_stgal <- antworten_stgal %>% group_by(Antwort,Ort) %>% summarise(occurences = n())

# Combine all together
dp11_together <- rbind(antworten_breg,antworten_dorn,antworten_kons,antworten_meer,
                       antworten_roman,antworten_stgal)

## Rebranding
dp11_together$Antwort[dp11_together$Antwort == "ja_au"] <- "Ja, im österreichischen Teil"
dp11_together$Antwort[dp11_together$Antwort == "ja_ch"] <- "Ja, im schweizerischen Teil"
dp11_together$Antwort[dp11_together$Antwort == "ja_de"] <- "Ja, im deutschen Teil"
dp11_together$Antwort[dp11_together$Antwort == "Nein, kann ich mir nicht vorstellen"] <- "Nein"
dp11_together$Antwort[dp11_together$Antwort == "vielleicht"] <- "Vielleicht"

# pdf(file = "to_deliver/chord_ferien_v2.pdf", width = 7, height = 7)
# chordDiagram(dp11_together)
# dev.off()

```

### Gründe keine Ferien zu machen
```{r eval=FALSE}
install.packages("wordcloud")
library(wordcloud)
install.packages("RColorBrewer")
library(RColorBrewer)
install.packages("wordcloud2")
library(wordcloud2)
install.packages("tm")
library(tm)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
dp12 <- data_all %>% select(.,c("te_gruende_tourist","te_tourist_einheimisch","befragungsort_list","te_anrainer_de","te_anrainer_ch","te_anrainer_au")) %>%
  filter(., te_tourist_einheimisch == "tourist")

dp12_de <- dp12 %>% select(., c("te_anrainer_de")) %>% na.omit()
dp12_ch <- dp12 %>% select(.,c("te_anrainer_ch")) %>% na.omit()
dp12_au <- dp12 %>% select(.,c("te_anrainer_au")) %>% na.omit()

# write.csv(dp12_de,"to_deliver/tables/gruende_keinFer_de.csv", row.names = F)
# write.csv(dp12_ch,"to_deliver/tables/gruende_keinFer_ch.csv", row.names = F)
# write.csv(dp12_au,"to_deliver/tables/gruende_keinFer_au.csv", row.names = F)
```

```{r}
dp13 <- data_all %>% select(., c("te_jahreszeit_attraktiv","te_jahreszeit_fruehling","te_jahreszeit_sommer",
                                 "te_jahreszeit_herbst","te_jahreszeit_winter"))

dp13_frue <- dp13 %>% select(., c("te_jahreszeit_fruehling"))
dp13_frue$te_jahreszeit_fruehling[dp13_frue$te_jahreszeit_fruehling == "1_1"] <- "sehr attraktiv"
dp13_frue$te_jahreszeit_fruehling[dp13_frue$te_jahreszeit_fruehling == "1_2"] <- "-"
dp13_frue$te_jahreszeit_fruehling[dp13_frue$te_jahreszeit_fruehling == "1_3"] <- "--"
dp13_frue$te_jahreszeit_fruehling[dp13_frue$te_jahreszeit_fruehling == "1_4"] <- "---"
dp13_frue$te_jahreszeit_fruehling[dp13_frue$te_jahreszeit_fruehling == "1_5"] <- "----"
dp13_frue$te_jahreszeit_fruehling[dp13_frue$te_jahreszeit_fruehling == "1_6"] <- "sehr unattraktiv"
dp13_frue <- dp13_frue %>% na.omit() %>% group_by(te_jahreszeit_fruehling) %>%
  summarise(occurences = n()) %>% mutate(percentage = round((occurences/172)*100,2),
                                         type = "Frühling")
dp13_frue$te_jahreszeit_fruehling <- factor(dp13_frue$te_jahreszeit_fruehling, levels = c("sehr attraktiv", "-","--","---","----","sehr unattraktiv"))
names(dp13_frue)[1] <- "Jahreszeit"


dp13_som <- dp13 %>% select(., c("te_jahreszeit_sommer"))
dp13_som$te_jahreszeit_sommer[dp13_som$te_jahreszeit_sommer == "2_1"] <- "sehr attraktiv"
dp13_som$te_jahreszeit_sommer[dp13_som$te_jahreszeit_sommer == "2_2"] <- "-"
dp13_som$te_jahreszeit_sommer[dp13_som$te_jahreszeit_sommer == "2_3"] <- "--"
dp13_som$te_jahreszeit_sommer[dp13_som$te_jahreszeit_sommer == "2_4"] <- "---"
dp13_som$te_jahreszeit_sommer[dp13_som$te_jahreszeit_sommer == "2_5"] <- "----"
dp13_som$te_jahreszeit_sommer[dp13_som$te_jahreszeit_sommer == "2_6"] <- "sehr unattraktiv"
dp13_som <- dp13_som %>% na.omit() %>% group_by(te_jahreszeit_sommer) %>%
  summarise(occurences = n()) %>% mutate(percentage = round((occurences/175)*100,2),
                                         type = "Sommer")
dp13_som$te_jahreszeit_sommer <- factor(dp13_som$te_jahreszeit_sommer, levels = c("sehr attraktiv", "-","--","---","----","sehr unattraktiv"))
names(dp13_som)[1] <- "Jahreszeit"


dp13_her <- dp13 %>% select(., c("te_jahreszeit_herbst"))
dp13_her$te_jahreszeit_herbst[dp13_her$te_jahreszeit_herbst == "3_1"] <- "sehr attraktiv"
dp13_her$te_jahreszeit_herbst[dp13_her$te_jahreszeit_herbst == "3_2"] <- "-"
dp13_her$te_jahreszeit_herbst[dp13_her$te_jahreszeit_herbst == "3_3"] <- "--"
dp13_her$te_jahreszeit_herbst[dp13_her$te_jahreszeit_herbst == "3_4"] <- "---"
dp13_her$te_jahreszeit_herbst[dp13_her$te_jahreszeit_herbst == "3_5"] <- "----"
dp13_her$te_jahreszeit_herbst[dp13_her$te_jahreszeit_herbst == "3_6"] <- "sehr unattraktiv"
dp13_her <- dp13_her %>% na.omit() %>% group_by(te_jahreszeit_herbst) %>%
  summarise(occurences = n()) %>% mutate(percentage = round((occurences/171)*100,2),
                                         type = "Herbst")
dp13_her$te_jahreszeit_herbst <- factor(dp13_her$te_jahreszeit_herbst, c("sehr attraktiv", "-","--","---","----","sehr unattraktiv"))
names(dp13_her)[1] <- "Jahreszeit"



dp13_win <- dp13 %>% select(., c("te_jahreszeit_winter"))
dp13_win$te_jahreszeit_winter[dp13_win$te_jahreszeit_winter == "4_1"] <- "sehr attraktiv"
dp13_win$te_jahreszeit_winter[dp13_win$te_jahreszeit_winter == "4_2"] <-"-"
dp13_win$te_jahreszeit_winter[dp13_win$te_jahreszeit_winter == "4_3"] <-"--"
dp13_win$te_jahreszeit_winter[dp13_win$te_jahreszeit_winter == "4_4"] <-"---"
dp13_win$te_jahreszeit_winter[dp13_win$te_jahreszeit_winter == "4_5"] <-"----"
dp13_win$te_jahreszeit_winter[dp13_win$te_jahreszeit_winter == "4_6"] <- "sehr unattraktiv"
dp13_win <- dp13_win %>% na.omit() %>% group_by(te_jahreszeit_winter) %>%
  summarise(occurences = n()) %>% mutate(percentage = round((occurences/167)*100,2),
                                         type = "Winter")
dp13_win$te_jahreszeit_winter <- factor(dp13_win$te_jahreszeit_winter, levels = c("sehr attraktiv", "-","--","---","----","sehr unattraktiv"))
names(dp13_win)[1] <- "Jahreszeit"


dp13_all <- rbind(dp13_frue,dp13_som,dp13_her,dp13_win)

## pie plot
p13_plot <- ggplot(data = dp13_all, aes(x = "", y = percentage, fill = Jahreszeit)) + 
    geom_bar(stat = "identity", position = position_fill()) +
    #geom_text(aes(label = percentage), position = position_fill(vjust = 0.5), size = 3) +
    coord_polar(theta = "y") + ggtitle("Wie attraktiv finden Sie die Jahreszeiten für einen Urlaub\nin der Bodenseeregion?") +  ylab("% Prozent") + facet_wrap(~ type) + scale_fill_manual(values = c("#4d4dff", "#ccccff", "#e6f2ff","#ffccee","#ff8080","#ff0000")) + 
  theme(plot.title = element_text(size = 11, face = "bold"),
          axis.title.x = element_text(size = 10,face = "bold"),
          axis.title.y = element_blank(),
          legend.title = element_blank(), legend.position='bottom',
          axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid  = element_blank())

#ggsave("to_deliver/insteadoflinear2.pdf")
```


```{r, warning=FALSE, message=FALSE}
library(circlize)
dp14 <- data_all %>% select(.,c("sdf_wohnort","te_tourist_einheimisch",
          "te_zeit_einkaufen_au","te_zeit_ausfluege_au","te_zeit_kontakte_au","te_zeit_gaststaetten_au",
          "te_zeit_kultur_au","te_zeit_spazieren_au","te_zeit_arbeiten_au",
          "te_zeit_einkaufen_de","te_zeit_ausfluege_de","te_zeit_kontakte_de","te_zeit_gaststaetten_de",
          "te_zeit_kultur_de","te_zeit_spazieren_de","te_zeit_arbeiten_de",
          "te_zeit_einkaufen_ch","te_zeit_ausfluege_ch","te_zeit_kontakte_ch","te_zeit_gaststaetten_ch",
          "te_zeit_kultur_ch","te_zeit_spazieren_ch","te_zeit_arbeiten_ch",
          "te_zeit_einkaufen_li","te_zeit_ausfluege_li","te_zeit_kontakte_li","te_zeit_gaststaetten_li",
          "te_zeit_kultur_li","te_zeit_spazieren_li","te_zeit_arbeiten_li")) %>%
  filter(.,te_tourist_einheimisch == "einheimisch")

t <- dp14 %>% filter(., sdf_wohnort == "li")

# replace values accross the dataframe
dp14[dp14 == "te_zeit_1"] <- "nie"
dp14[dp14 == "te_zeit_2"] <- "1-2x pro Jahr"
dp14[dp14 == "te_zeit_3"] <- "3-4x pro Jahr"
dp14[dp14 == "te_zeit_4"] <- "5-12x pro Jahr"
dp14[dp14 == "ch"] <- "Schweiz"
dp14[dp14 == "au"] <- "Österreich"
dp14[dp14 == "de"] <- "Deutschland"



## Austria
dp14_au <- dp14 %>% select(.,c("sdf_wohnort","te_zeit_einkaufen_au","te_zeit_ausfluege_au","te_zeit_kontakte_au","te_zeit_gaststaetten_au","te_zeit_kultur_au","te_zeit_spazieren_au","te_zeit_arbeiten_au")) %>% 
  filter(sdf_wohnort != "au")

names(dp14_au) <- c("sdf_wohnort","Einkaufen","Ausflüge","Freunden und Familie","Besuch von Gaststätten","Kulturangeboten","Spazierengehen","Arbeiten")

dp14_au <- pivot_longer(dp14_au, c("Einkaufen","Ausflüge","Freunden und Familie","Besuch von Gaststätten","Kulturangeboten","Spazierengehen","Arbeiten")) %>% na.omit() %>% group_by(sdf_wohnort,name,value) %>%
  summarise(occurences = n())

grid.col = c(Schweiz = "#de2d26", Österreich = "#cccccc",Deutschland = "#252525")

## Ohne Nie Werte
dp14_au_ohne<-subset(dp14_au, value!="nie")

# pdf(file = "to_deliver/dp14_au_ohne.pdf", width = 7, height = 7)
# chordDiagram(dp14_au_ohne,grid.col = grid.col)
# dev.off()

## Nun Nie Werte
dp14_au_nie<-subset(dp14_au, value == "nie")
pdf(file = "to_deliver/dp14_au_nie.pdf", width = 7, height = 7)
chordDiagram(dp14_au_nie,grid.col = grid.col)
dev.off()

## Deutschland
dp14_de <- dp14 %>% select(.,c("sdf_wohnort","te_zeit_einkaufen_de","te_zeit_ausfluege_de","te_zeit_kontakte_de","te_zeit_gaststaetten_de","te_zeit_kultur_de","te_zeit_spazieren_de","te_zeit_arbeiten_de")) %>% 
  filter(sdf_wohnort != "de")

names(dp14_de) <- c("sdf_wohnort","Einkaufen","Ausflüge","Freunden und Familie","Besuch von Gaststätten","Kulturangeboten","Spazierengehen","Arbeiten")

dp14_de <- pivot_longer(dp14_de, c("Einkaufen","Ausflüge","Freunden und Familie","Besuch von Gaststätten","Kulturangeboten","Spazierengehen","Arbeiten")) %>% na.omit() %>% group_by(sdf_wohnort,name,value) %>%
  summarise(occurences = n())

# pdf(file = "to_deliver/dp14_de.pdf", width = 7, height = 7)
# chordDiagram(dp14_de, grid.col = grid.col)
# dev.off()

# Ohne Nie Werte
dp14_de_ohne<-subset(dp14_de, value!="nie")

# pdf(file = "to_deliver/dp14_de_ohne.pdf", width = 7, height = 7)
# chordDiagram(dp14_de_ohne,grid.col = grid.col)
# dev.off()

## Nun Nie Werte
dp14_de_nie<-subset(dp14_de, value == "nie")
# pdf(file = "to_deliver/dp14_de_nie.pdf", width = 7, height = 7)
# chordDiagram(dp14_de_nie,grid.col = grid.col)
# dev.off()

## Schweiz
dp14_ch <- dp14 %>% select(.,c("sdf_wohnort","te_zeit_einkaufen_ch","te_zeit_ausfluege_ch","te_zeit_kontakte_ch","te_zeit_gaststaetten_ch","te_zeit_kultur_ch","te_zeit_spazieren_ch","te_zeit_arbeiten_ch")) %>% 
  filter(sdf_wohnort != "ch")

names(dp14_ch) <- c("sdf_wohnort","Einkaufen","Ausflüge","Freunden und Familie","Besuch von Gaststätten","Kulturangeboten","Spazierengehen","Arbeiten")

dp14_ch <- pivot_longer(dp14_ch, c("Einkaufen","Ausflüge","Freunden und Familie","Besuch von Gaststätten","Kulturangeboten","Spazierengehen","Arbeiten")) %>% na.omit() %>% group_by(sdf_wohnort,name,value) %>%
  summarise(occurences = n())

# Ohne Nie Werte
dp14_ch_ohne<-subset(dp14_ch, value!="nie")

pdf(file = "to_deliver/dp14_ch_ohne.pdf", width = 7, height = 7)
chordDiagram(dp14_ch_ohne,grid.col = grid.col)
dev.off()

## Nun Nie Werte
dp14_ch_nie<-subset(dp14_ch, value == "nie")
pdf(file = "to_deliver/dp14_ch_nie.pdf", width = 7, height = 7)
chordDiagram(dp14_ch_nie,grid.col = grid.col)
dev.off()

# 
# pdf(file = "to_deliver/dp14_ch.pdf", width = 7, height = 7)
chordDiagram(dp14_ch, grid.col = grid.col,directional = 1)
# dev.off()

css5 <- scale_fill_manual(values = c("#bababa", "#f4a582","#ca0020","#404040"),
                   labels = c("1-2x pro Jahr", "3-4x pro Jahr", "5-12x pro Jahr","nie"))

## CH PLUS
dp14_ch_PLUS <- ggplot(data = dp14_ch, aes(x = sdf_wohnort, y = occurences, fill = value)) +
  geom_col(position = "dodge", alpha = 0.8) + xlab(" ") + ylab("Wie häufig (n)") +
  geom_text(aes(label = occurences),
            position=position_dodge(width=0.9), size = 3,vjust=-0.5) + facet_wrap(~ name) + 
  ggtitle("Aus welchen Gründen und wie häufig waren Sie im schweizerischen Teil?") + ylim(0,100) + 
  theme(plot.title = element_text(size = 11, face = "bold"),legend.title = element_blank(), legend.position="bottom",
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10,face = "bold"),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10,face = "bold")) + css5

ggsave("to_deliver/dp14_ch_PLUS.pdf")

## AU PLUS
dp14_au_PLUS <- ggplot(data = dp14_au, aes(x = sdf_wohnort, y = occurences, fill = value)) +
  geom_col(position = "dodge", alpha = 0.8) + xlab(" ") + ylab("Wie häufig (n)") +
  geom_text(aes(label = occurences),
            position=position_dodge(width=0.9), size = 3,vjust=-0.5) + facet_wrap(~ name) + 
  ggtitle("Aus welchen Gründen und wie häufig waren Sie im österreichischen Teil?") + ylim(0,100) + 
  theme(plot.title = element_text(size = 11, face = "bold"),legend.title = element_blank(), legend.position="bottom",
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10,face = "bold"),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10,face = "bold")) + css5

#ggsave("to_deliver/dp14_au_PLUS.pdf")

## DE PLUS
dp14_de_PLUS <- ggplot(data = dp14_de, aes(x = sdf_wohnort, y = occurences, fill = value)) +
  geom_col(position = "dodge", alpha = 0.8) + xlab(" ") + ylab("Wie häufig (n)") +
  geom_text(aes(label = occurences),
            position=position_dodge(width=0.9), size = 3,vjust=-0.5) + facet_wrap(~ name) + 
  ggtitle("Aus welchen Gründen und wie häufig waren Sie im deutschen Teil?") + ylim(0,100) + 
  theme(plot.title = element_text(size = 11, face = "bold"),legend.title = element_blank(), legend.position="bottom",
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10,face = "bold"),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10,face = "bold")) + css5

#ggsave("to_deliver/dp14_de_PLUS.pdf")
```



